# 利用するdocker-comnposeのバージョン
version: '3.9'

# アプリケーションで動かすための各要素
services:
  # api用
  django:
    # 起動するコンテナの設定
    build:
      # ディレクトリの指定
      context: .
      # 使用するDockerfileの名前を指定、「Dockerfile」という名前なら省略可能
      dockerfile: Dockerfile
    container_name: django_container
    # ディレクトリのマウントの設定、:前がホストのディレクトリ、:後がコンテナのディレクトリ
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    # ポート設定、:前がホスト側のポート、:あとがコンテナ側のポート
    ports:
      - "8000:8080"
    # Tele-TYpewriter、コンテナ起動後に終了させないための設定
    tty: true
