# 利用するdocker-comnposeのバージョン
version: '3.9'

# アプリケーションで動かすための各要素
services:
  # api用
  django:
    # 起動するコンテナの設定
    build:
      # ディレクトリの指定
      context: .
      # 使用するDockerfileの名前を指定、「Dockerfile」という名前なら省略可能
      dockerfile: Dockerfile
    container_name: django_container
    # ディレクトリのマウントの設定、:前がホストのディレクトリ、:後がコンテナのディレクトリ
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    # ポート設定、:前がホスト側のポート、:あとがコンテナ側のポート
    ports:
      - "8000:8080"
    # Tele-TYpewriter、コンテナ起動後に終了させないための設定
    tty: true
    depends_on:
      - db

  # db用
  db:
    image: mysql:5.7
    container_name: mysql_container
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
    # 文字コードの設定
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
